blueprint:
  name: "Hue Dimmer Beyond Lighting 0.4.0b"
  author: Michael Westlund <michael@westlund.org>
  description: >
    <h2>A comprehensive control blueprint for the Philips Hue Dimmer Switch</h2>
    <h1><i>Short press controls lights. Long press controls your home.</i></h1>
    <p>In its basic configuration it just controls the lights, but long press of the on/off buttons can be configured to do literally anything Home Assistant can do.
    <p><b>Short presses on the dim</b> buttons provide precise, predictable lighting control using configurable brightness steps.<br />
    <b>Long presses on the dim</b> buttons continuously dims the lights up until the button is released.<br />
    <p><b>Short presses on the on/off</b> buttons turns the light on or off using the current setting.<br />
    <b>Long presses on the on/off</b> buttons unlock unrestricted Home Assistant actions.<br />
    <p><i>Any action supported by Home Assistant can be executed — lighting, power, scenes, scripts, shutdown sequences, or entire environments.</i>
    <p>This blueprint intentionally collapses lighting control and system control into a single, consistent interaction model. Designed to replace multiple automations with one.
    <p>
    <ha-alert alert-type="warning">Warning: This is still in beta. Fedback is much appreciated. Please conmtact me at &lt;michael@westlund.org&gt; or provide feedback in the GIthub repository.</ha-alert>
  source_url: https://github.com/westlund/hassio-blueprints/blob/main/blueprints/automation/papamike/phd_12.yaml
  domain: automation
  homeassistant:
    min_version: 2024.6.0
  input:
    basic:
      name: Basic
      description: "Dim up and down continuously or step by step, or turn on and off. See Advanced Configuration below for power features."
      icon: mdi:lightbulb
      collapsed: false
      input:
        dimmer_device:
          name: Dimmer Device
          description: "A Philips Hue Dimmmer Switch v1 or v2."
          default: []
          selector:
            device:
              filter:
                - manufacturer: Philips
                  model_id: "324131092621"
                - manufacturer: Philips
                  model_id: "929002398602"
        lights_target:
          name: Lights
          description: "Select dimmable light entities directly or a target that contains dimmable lights."
          default: []
          selector:
            target:
              entity:
                - supported_features:
                    - light.LightEntityFeature.TRANSITION
                  domain: light
                - integration: mqtt
                  domain: light
    advanced:
      name: Advanced configuration
      description: "Advanced features"
      icon: mdi:cog
      collapsed: true
      input:
        step_dimmer_speed:
          name: Step Dimmer Transition
          description: "The transition time in seconds on each press of the dim up or down buttons."
          selector:
            number:
              min: 0.1
              max: 1.0
              step: 0.1
              mode: slider
          default: 0.5
        step_dimmer_change:
          name: Step Dimmer Change
          description: "The number of steps up or down to change the brightness on each press of the dim up or down buttons."
          selector:
            number:
              min: 1
              max: 255
              step: 1
              mode: slider
          default: 26
        continuous_dimmer_step:
          name: Continuous Dimmer Speed
          description: "The speed with which the continuois dimmer dims up or down."
          selector:
            number:
              min: 1
              max: 32
              step: 1
              mode: slider
          default: 16
        on_action:
          name: Additional action for long press on
          selector:
            action: {}
          default: []
        off_action:
          name: Additional action for long press off
          selector:
            action: {}
          default: []

mode: restart
max_exceeded: silent

triggers:
  - domain: mqtt
    device_id: !input dimmer_device
    type: action
    subtype: on_press_release
    id: on-press-release
    trigger: device
  - domain: mqtt
    device_id: !input dimmer_device
    type: action
    subtype: off_press_release
    id: off-press-release
    trigger: device
  - domain: mqtt
    device_id: !input dimmer_device
    type: action
    subtype: on_hold
    id: on-hold
    trigger: device
  - domain: mqtt
    device_id: !input dimmer_device
    type: action
    subtype: up_hold
    id: dim-up-continuous
    trigger: device
  - domain: mqtt
    device_id: !input dimmer_device
    type: action
    subtype: down_hold
    id: dim-down-continuous
    trigger: device
  - domain: mqtt
    device_id: !input dimmer_device
    type: action
    subtype: up_hold_release
    trigger: device
    id: dim-stop
  - domain: mqtt
    device_id: !input dimmer_device
    type: action
    subtype: down_hold_release
    trigger: device
    id: dim-stop
  - domain: mqtt
    device_id: !input dimmer_device
    type: action
    subtype: up_press_release
    id: dim-up-step
    trigger: device
  - domain: mqtt
    device_id: !input dimmer_device
    type: action
    subtype: down_press_release
    id: dim-down-step
    trigger: device
  - domain: mqtt
    device_id: !input dimmer_device
    type: action
    subtype: off_hold
    id: off-hold
    trigger: device

conditions: []

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: on-hold
        sequence:
          - data:
              transition: !input step_dimmer_speed
              kelvin: 3600
              brightness_pct: 100
            target: !input lights_target
            action: light.turn_on
            enabled: true
          - choose: []
            default: !input on_action
      - conditions:
          - condition: trigger
            id: off-hold
        sequence:
          - data:
              transition: !input step_dimmer_speed
            target: !input lights_target
            action: light.turn_off
          - choose: []
            default: !input off_action
      - conditions:
          - condition: trigger
            id: on-press-release
        sequence:
          - data:
              transition: !input step_dimmer_speed
            target: !input lights_target
            action: light.turn_on
      - conditions:
          - condition: trigger
            id: off-press-release
        sequence:
          - action: light.turn_off
            data:
              transition: !input step_dimmer_speed
            target: !input lights_target
      - conditions:
        - condition: trigger
          id: dim-up-continuous
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: dim-up-continuous
              sequence:
                - action: light.turn_on
                  data:
                    transition: 0.2
                    brightness_step: !input continuous_dimmer_step
                  target: !input lights_target
                - delay:
                    # hours: 0
                    # minutes: 0
                    # seconds: !input continuous_dimmer_speed
                    milliseconds: 200
      - conditions:
          - condition: trigger
            id: dim-stop
        sequence:
      - conditions:
        - condition: trigger
          id: dim-down-continuous
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: dim-down-continuous
              sequence:
                - variables:
                    step: !input continuous_dimmer_step
                - data:
                    transition: 0.2
                    brightness_step: "{{ -step }}"
                  target: !input lights_target
                  action: light.turn_on
                - delay:
                    # hours: 0
                    # minutes: 0
                    # seconds: !input continuous_dimmer_speed
                    milliseconds: 200
      - conditions:
          - condition: trigger
            id: dim-up-step
        sequence:
          - data:
              brightness_step: !input step_dimmer_change
              transition: !input step_dimmer_speed
            target: !input lights_target
            action: light.turn_on
      - conditions:
          - condition: trigger
            id: dim-down-step
        sequence:
          - variables:
              step: !input step_dimmer_change
          - data:
              brightness_step: "{{ -step }}"
              transition: !input step_dimmer_speed
            target: !input lights_target
            action: light.turn_on
